
Flags = -m32
CPP = g++
all: zad3 zad1 zad8


zad1: 
	$(CPP) $(Flags) zad1.cpp -o zad1 

zad3: 
	$(CPP) $(Flags) zad3.cpp -o zad3 

zad8:
	$(CPP) $(Flags) zad8.cpp -o zad8

clean:
	rm -f zad1 zad3 zad8

